### PR TITLE
fix: no exit if not ancestor of current commit

### LINKED ISSUE #19: First build on a branch with no changes fails
If I create a new branch and push to the repository without adding a new commit, I get the following error:

```
checking if foo a new branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 41822  100 41822    0     0   559k      0 --:--:-- --:--:-- --:--:--  559k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 58216  100 58216    0     0   719k      0 --:--:-- --:--:-- --:--:--  719k
----------------------------------------------------------------------------------------------------
yes,foo is new and 37dc2b3b5fc1f729e7d35ec178cd67873d7519f0 is its only commit
finding most recent ancestor commit from any other branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 68958  100 68958    0     0   370k      0 --:--:-- --:--:-- --:--:--  367k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 68958  100 68958    0     0   534k      0 --:--:-- --:--:-- --:--:--  534k
Exited with code 1
```

### LINKED ISSUE #21: Mysterious exit code 1
### Orb version

`0.4.10`

### What happened

Branch off master, push an insignificant change, exits 1

Has happened twice to me.

- First time I fixed it by updating to latest version of orb.
- Second time (this time) I fixed it by setting `debug: true`. Then I removed `debug: true` and it continued to work.

```
checking if fix/base-bash-safe-export is a new branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100  112k  100  112k    0     0  1120k      0 --:--:-- --:--:-- --:--:-- 1122k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 72190  100 72190    0     0   570k      0 --:--:-- --:--:-- --:--:--  573k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 54585  100 54585    0     0   586k      0 --:--:-- --:--:-- --:--:--  592k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 73775  100 73775    0     0   744k      0 --:--:-- --:--:-- --:--:--  750k
----------------------------------------------------------------------------------------------------
yes, fix/base-bash-safe-export is new and 667069510cd23599dde2c590a0f3ce5e5d07a2ed is its only commit
finding most recent ancestor commit from any other branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 54585  100 54585    0     0   479k      0 --:--:-- --:--:-- --:--:--  484k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 54585  100 54585    0     0   635k      0 --:--:-- --:--:-- --:--:--  642k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 73775  100 73775    0     0   891k      0 --:--:-- --:--:-- --:--:--  900k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 73775  100 73775    0     0   460k      0 --:--:-- --:--:-- --:--:--  461k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 75923  100 75923    0     0   503k      0 --:--:-- --:--:-- --:--:--  500k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 75923  100 75923    0     0   748k      0 --:--:-- --:--:-- --:--:--  756k
Exited with code 1
```

### Expected behavior

Branch off master, push an insignificant change, exits 0.

Related:

- https://github.com/iynere/compare-url/issues/11
- https://github.com/iynere/compare-url/issues/17

### PR DESCRIPTION
**Pull request by jasonkuhrt**
fixes #21 
fixes #19

### CODE REVIEW

**Comment by iynere** [comment]
ahhhhh thank you, I knew there was a bug like this but couldn't pin it down

**Comment by iynere** [comment]
@jasonkurt thanks so much, I'm about to merge, please try the new version (it will auto-publish) & let me know if it works

**Comment by jasonkuhrt** [comment]
@iynere will do! And thanks for all your work on this orb 🙏

**Comment by jasonkuhrt** [comment]
@iynere Now I'm hitting the else case

```
unknown return code 128 from git merge-base with base commit 51ea9ce0675f699478b74defbb0afbba082afef2, from job 1852
```

**Comment by iynere** [comment]
@jasonkuhrt not sure what that might mean—can you debug a bit ?

**Comment by jasonkuhrt** [comment]
Yeah I'll try to dig next time it happens, probably within a week or so.

**Comment by iynere** [comment]
awesome !! @jasonkuhrt 

if we broke something, i'm sure others will let us know, as well, so hopefully we can crowdsource a fix shortly ^_^

**Pull request merged**
